"area:backend":
  - changed-files:
    - any-glob-to-any-file:
      - 'server/**'

"area:frontend":
  - changed-files:
    - any-glob-to-any-file:
      - 'client/**'

"area:ci-cd":
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**'

"area:root":
  - changed-files:
    - any-glob-to-any-file:
      - '*'